version: 2
updates:
  - package-ecosystem: "npm"
    commit-message:
      prefix: 'chore'
      include: 'scope'
    directory: "/"
    ignore:
      - dependency-name: '@types/node'
        update-types: [ 'version-update:semver-major' ]
    schedule:
      interval: 'daily'
    versioning-strategy: 'increase'

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"
