env:
  # Most of the code here will not be for the browser; use overrides to indicate
  # browser code.
  browser: false
  node: true

extends:
  - 'plugin:@ianwremmel/ianwremmel/modern'
  - 'plugin:@ianwremmel/ianwremmel/typescript'
  - 'prettier'

ignorePatterns:
  - dist

overrides:
  - files:
      - '**/*.ts'
      - '**/*.tsx'
    parserOptions:
      sourceType: module

  - files:
      - '**/*.test.*'
      - '**/__mocks__/**/*'
    env:
      jest: true
    rules:
      require-jsdoc: off

  - files:
      - '**/*.graphql'
      - '**/*.graphqls'
    extends: 'plugin:@graphql-eslint/schema-recommended'
    rules:
      # Since we're building a bunch of different schema, not all of the shared
      # schema will be used in each combined schema ,so this rule can't be
      # usefully enforced.
      '@graphql-eslint/no-unreachable-types': off
      strict: off

  - files:
      - 'src/runtime/**'
    rules:
      no-console: error

  - files:
      - '**/__generated__/**/*'
    rules:
      complexity: off

parserOptions:
  sourceType: 'script'
