AWSTemplateFormatVersion: '2010-09-09'
Conditions:
  IsProd:
    Fn::Equals:
      - Ref: StageName
      - production
Globals:
  Function:
    Environment:
      Variables:
        TABLE_USER_SESSION:
          Ref: TableUserSession
    Handler: index.handler
    MemorySize: 256
    Runtime: nodejs18.x
    Timeout: 30
    Tracing: Active
Outputs:
  TableUserSession:
    Description: The name of the DynamoDB table for TableUserSession
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-TableUserSession
      Value:
        Ref: TableUserSession
    Value:
      Ref: TableUserSession
Parameters:
  LogRetentionInDays:
    Default: 3
    Description: Log retention in days
    Type: Number
  StageName:
    AllowedValues:
      - development
      - production
      - test
    Default: development
    Description: The name of the stage
    Type: String
Resources:
  FnTriggerUSUpsert7d1674e2:
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - ./index
        External:
          - '@aws-sdk/*'
        Minify: false
        Sourcemap: true
        Target: es2020
    Properties:
      CodeUri: trigger--user-session--upsert
      DeadLetterQueue:
        TargetArn:
          Fn::GetAtt:
            - FnTriggerUSUpsert7d1674e2EventBridgeDLQ
            - Arn
        Type: SQS
      Events:
        UPSERT:
          Properties:
            DeadLetterConfig:
              Arn:
                Fn::GetAtt:
                  - FnTriggerUSUpsert7d1674e2DLQ
                  - Arn
            EventBusName: default
            Pattern:
              detail:
                dynamodb:
                  NewImage:
                    _et:
                      S:
                        - UserSession
              detail-type:
                - INSERT
                - MODIFY
              resources:
                - Fn::GetAtt:
                    - TableUserSession
                    - Arn
              source:
                - TableUserSession.UserSession
          Type: EventBridgeRule
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - CloudWatchLambdaInsightsExecutionRolePolicy
        - CloudWatchPutMetricPolicy: {}
        - SQSSendMessagePolicy:
            QueueName:
              Fn::GetAtt:
                - FnTriggerUSUpsert7d1674e2DLQ
                - QueueName
    Type: AWS::Serverless::Function
  FnTriggerUSUpsert7d1674e2DLQ:
    Properties:
      KmsMasterKeyId: alias/aws/sqs
    Type: AWS::SQS::Queue
  FnTriggerUSUpsert7d1674e2EventBridgeDLQ:
    Properties:
      KmsMasterKeyId: alias/aws/sqs
    Type: AWS::SQS::Queue
  FnTriggerUSUpsert7d1674e2LogGroup:
    Properties:
      LogGroupName:
        Fn::Sub: /aws/lambda/${FnTriggerUSUpsert7d1674e2}
      RetentionInDays:
        Ref: LogRetentionInDays
    Type: AWS::Logs::LogGroup
  TableUserSession:
    Properties:
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled:
          Fn::If:
            - IsProd
            - true
            - false
      SSESpecification:
        SSEEnabled:
          Fn::If:
            - IsProd
            - true
            - false
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      Tags:
        - Key: StageName
          Value:
            Ref: StageName
        - Key: TableName
          Value: TableUserSession
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
    Type: AWS::DynamoDB::Table
  TableUserSessionCDCDispatcher:
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - ./index
        External:
          - '@aws-sdk/*'
        Minify: false
        Sourcemap: true
        Target: es2020
    Properties:
      CodeUri: dispatcher-table-user-session
      Events:
        Stream:
          Properties:
            BatchSize: 10
            FunctionResponseTypes:
              - ReportBatchItemFailures
            MaximumRetryAttempts: 3
            StartingPosition: TRIM_HORIZON
            Stream:
              Fn::GetAtt:
                - TableUserSession
                - StreamArn
          Type: DynamoDB
      MemorySize: 384
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - CloudWatchLambdaInsightsExecutionRolePolicy
        - CloudWatchPutMetricPolicy: {}
        - EventBridgePutEventsPolicy:
            EventBusName: default
      Timeout: 60
    Type: AWS::Serverless::Function
  TableUserSessionCDCDispatcherLogGroup:
    Properties:
      LogGroupName:
        Fn::Sub: /aws/lambda/${TableUserSessionCDCDispatcher}
      RetentionInDays:
        Ref: LogRetentionInDays
    Type: AWS::Logs::LogGroup
Transform: AWS::Serverless-2016-10-31
