AWSTemplateFormatVersion: '2010-09-09'
Conditions:
  IsProd:
    Fn::Equals:
      - Ref: StageName
      - production
Globals:
  Function:
    Environment:
      Variables:
        TABLE_ACCOUNTS:
          Ref: TableAccounts
        TABLE_EMAIL:
          Ref: TableEmail
    Handler: index.handler
    MemorySize: 256
    Runtime: nodejs18.x
    Timeout: 30
    Tracing: Active
Outputs:
  TableAccounts:
    Description: The name of the DynamoDB table for TableAccounts
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-TableAccounts
      Value:
        Ref: TableAccounts
    Value:
      Ref: TableAccounts
  TableEmail:
    Description: The name of the DynamoDB table for TableEmail
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-TableEmail
      Value:
        Ref: TableEmail
    Value:
      Ref: TableEmail
Parameters:
  LogRetentionInDays:
    Default: 3
    Description: Log retention in days
    Type: Number
  StageName:
    AllowedValues:
      - development
      - production
      - test
    Default: development
    Description: The name of the stage
    Type: String
Resources:
  FnHandlerSInsertAa23d7fc7:
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - ./index
        External:
          - '@aws-sdk/*'
        Minify: false
        Sourcemap: true
        Target: es2020
    Properties:
      CodeUri: enricher--subscription--insert--account
      DeadLetterQueue:
        TargetArn:
          Fn::GetAtt:
            - FnHandlerSInsertAa23d7fc7EventBridgeDLQ
            - Arn
        Type: SQS
      Events:
        INSERT:
          Properties:
            DeadLetterConfig:
              Arn:
                Fn::GetAtt:
                  - FnHandlerSInsertAa23d7fc7DLQ
                  - Arn
            EventBusName: default
            Pattern:
              detail:
                dynamodb:
                  NewImage:
                    _et:
                      S:
                        - Subscription
              detail-type:
                - INSERT
              resources:
                - Fn::GetAtt:
                    - TableAccounts
                    - Arn
              source:
                - TableAccounts.Subscription
          Type: EventBridgeRule
      MemorySize: 256
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - CloudWatchLambdaInsightsExecutionRolePolicy
        - CloudWatchPutMetricPolicy: {}
        - DynamoDBCrudPolicy:
            TableName:
              Ref: TableAccounts
        - SQSSendMessagePolicy:
            QueueName:
              Fn::GetAtt:
                - FnHandlerSInsertAa23d7fc7DLQ
                - QueueName
      Timeout: 30
    Type: AWS::Serverless::Function
  FnHandlerSInsertAa23d7fc7DLQ:
    Properties:
      KmsMasterKeyId: alias/aws/sqs
    Type: AWS::SQS::Queue
  FnHandlerSInsertAa23d7fc7EventBridgeDLQ:
    Properties:
      KmsMasterKeyId: alias/aws/sqs
    Type: AWS::SQS::Queue
  FnHandlerSInsertAa23d7fc7LogGroup:
    Properties:
      LogGroupName:
        Fn::Sub: /aws/lambda/${FnHandlerSInsertAa23d7fc7}
      RetentionInDays:
        Ref: LogRetentionInDays
    Type: AWS::Logs::LogGroup
  TableAccounts:
    Properties:
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: lsi1sk
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      LocalSecondaryIndexes:
        - IndexName: lsi1
          KeySchema:
            - AttributeName: pk
              KeyType: HASH
            - AttributeName: lsi1sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled:
          Fn::If:
            - IsProd
            - true
            - false
      SSESpecification:
        SSEEnabled:
          Fn::If:
            - IsProd
            - true
            - false
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      Tags:
        - Key: StageName
          Value:
            Ref: StageName
        - Key: TableName
          Value: TableAccounts
    Type: AWS::DynamoDB::Table
  TableAccountsCDCDispatcher:
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - ./index
        External:
          - '@aws-sdk/*'
        Minify: false
        Sourcemap: true
        Target: es2020
    Properties:
      CodeUri: dispatcher-table-accounts
      Events:
        Stream:
          Properties:
            BatchSize: 10
            FunctionResponseTypes:
              - ReportBatchItemFailures
            MaximumRetryAttempts: 3
            StartingPosition: TRIM_HORIZON
            Stream:
              Fn::GetAtt:
                - TableAccounts
                - StreamArn
          Type: DynamoDB
      MemorySize: 384
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - CloudWatchLambdaInsightsExecutionRolePolicy
        - CloudWatchPutMetricPolicy: {}
        - EventBridgePutEventsPolicy:
            EventBusName: default
      Timeout: 60
    Type: AWS::Serverless::Function
  TableAccountsCDCDispatcherLogGroup:
    Properties:
      LogGroupName:
        Fn::Sub: /aws/lambda/${TableAccountsCDCDispatcher}
      RetentionInDays:
        Ref: LogRetentionInDays
    Type: AWS::Logs::LogGroup
  TableEmail:
    Properties:
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled:
          Fn::If:
            - IsProd
            - true
            - false
      SSESpecification:
        SSEEnabled:
          Fn::If:
            - IsProd
            - true
            - false
      Tags:
        - Key: StageName
          Value:
            Ref: StageName
        - Key: TableName
          Value: TableEmail
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
    Type: AWS::DynamoDB::Table
Transform: AWS::Serverless-2016-10-31
