#!/usr/bin/env bash

set -euo pipefail

for file in $(find examples -mindepth 1 -maxdepth 1 -type d); do
  stackname=$(echo "$file" | awk -F/ '{print $2}' | sed -r 's/(^|[-_ ]+)([0-9a-z])/\U\2/g')
  sam deploy \
    --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND \
    --resolve-s3 \
    --template "$file/__generated__/template.yml" \
    --stack-name "$stackname" \
    --region us-east-1 || true
done
