import type {DumpOptions} from 'js-yaml';

export interface CloudformationPluginConfig {
  /**
   * Path to the actions generated by the ActionPlugin. Relative to the codegen
   * config file.
   */
  actionsModuleId: string;
  /**
   * Path to the dependencies file to be injected at runtime. Relative to the
   * codegen config file
   */
  dependenciesModuleId: string;

  /**
   * Path to an existing CloudFormation template to merge with the generated
   * template.
   */
  sourceTemplate?: string;
  outputConfig?: {
    format?: 'json' | 'yaml';
    yamlConfig?: Partial<DumpOptions>;
  };
}
